In [1]:
! pip install transformers

     |████████████████████████████████| 2.3MB 4.0MB/s 
     |████████████████████████████████| 901kB 36.9MB/s 
     |████████████████████████████████| 3.3MB 38.3MB/s 


In [2]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [3]:
from transformers import BertTokenizer
bert_token=BertTokenizer.from_pretrained('bert-base-cased')

In [4]:
bert_token.cls_token

'[CLS]'

In [6]:
enc=bert_token.encode('hi, this is me 13am')
print(enc)
dec=bert_token.decode(enc)
print(type(dec))
dec

[101, 20844, 117, 1142, 1110, 1143, 1492, 2312, 102]
<class 'str'>


'[CLS] hi, this is me 13am [SEP]'

In [7]:
from transformers import DistilBertTokenizer,TFDistilBertModel

distilbert='distilbert-base-uncased'
db=DistilBertTokenizer.from_pretrained(distilbert)
model=TFDistilBertModel.from_pretrained(distilbert)

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['vocab_layer_norm', 'vocab_transform', 'vocab_projector', 'activation_13']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [10]:
e=db.encode('hi this is my new notebook')
print(e)

input=tf.constant(e)[None,:]
print(type(input))
print(input)

output=model(input)
print(type(output))
print(output)


[101, 7632, 2023, 2003, 2026, 2047, 14960, 102]
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([[  101  7632  2023  2003  2026  2047 14960   102]], shape=(1, 8), dtype=int32)
<class 'transformers.modeling_tf_outputs.TFBaseModelOutput'>
TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
array([[[-0.04593655,  0.00333157,  0.21549799, ...,  0.05561512,
          0.20313409,  0.37936872],
        [ 0.32101423,  0.35053447,  0.73918694, ...,  0.18025701,
          0.26806036, -0.26288447],
        [-0.6463917 , -0.0815424 ,  0.53559387, ..., -0.22861466,
          0.11069999,  0.06140999],
        ...,
        [-0.15034632, -0.14570042,  0.63939047, ...,  0.08729231,
          0.12402102, -0.3376753 ],
        [-0.1367209 , -0.14465354, -0.07546519, ...,  0.43752825,
         -0.02247209, -0.01410656],
        [ 0.86645526,  0.25425673, -0.34229544, ...,  0.22595912,
         -0.55030876, -0.35053018]]], dtype=float32)>, hidden_states=

In [19]:
output[0][0,0,:]

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([-4.59365547e-02,  3.33157182e-03,  2.15497985e-01, -2.23599851e-01,
       -1.30577400e-01, -2.82631487e-01,  2.82606781e-01,  3.71641725e-01,
       -4.55870070e-02, -3.01241010e-01,  4.28210981e-02, -1.69603467e-01,
       -1.24899462e-01,  3.21640968e-01,  7.73478523e-02,  1.48856714e-01,
       -2.10174695e-01,  3.08918804e-01,  1.97036892e-01, -1.09222084e-02,
        1.70849822e-02, -2.74125189e-01,  5.83199970e-02, -6.75969496e-02,
        3.20554823e-02, -8.91286805e-02, -8.00686702e-03, -2.22610757e-02,
        1.34012952e-01, -5.89258820e-02,  2.27166973e-02,  8.28490928e-02,
        2.07041763e-02, -6.64471835e-02,  1.72127753e-01,  4.17116098e-02,
       -1.46486044e-01, -1.16157338e-01, -1.08736612e-01,  1.53998479e-01,
       -1.64881974e-01, -8.35725963e-02,  2.11633533e-01, -3.41286436e-02,
        4.86753657e-02, -2.60719031e-01, -2.44681835e+00, -3.92898396e-02,
       -6.15592189e-02, -9.42967981e-02,  3.76304507

In [23]:
# For more hidden layers for feature extraction ->> use DistilBertConfig

from transformers import DistilBertConfig

conf=DistilBertConfig.from_pretrained(distilbert,output_hidden_state=True)

e = db.encode("Hello, my dog is cute")
input = tf.constant(e)[None, :]  # Batch size 1 
model = TFDistilBertModel.from_pretrained(distilbert, config=conf)
print(model.config)

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['vocab_layer_norm', 'vocab_transform', 'vocab_projector', 'activation_13']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


DistilBertConfig {
  "_name_or_path": "distilbert-base-uncased",
  "activation": "gelu",
  "architectures": [
    "DistilBertForMaskedLM"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "transformers_version": "4.6.0",
  "vocab_size": 30522
}



In [24]:
out=model(input)
print(len(out))

1
